# Commands:
# watch -n 1 nvidia-smi : check GPU usage
# ollama pull [model]
# ollama list
# ollama run deepseek-r1:1.5b "Think carefully and tell me what's the meaning of life"
services:
  ollama:
    container_name: ollama
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ./.data:/root/.ollama
      - ./.script:/root
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_LLM_LIBRARY=cuda
      - OLLAMA_CUDA_VISIBLE_DEVICES=0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    networks:
      - ollama-network

  webui:
    container_name: ollama-webui
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:8080"  # Access UI at http://localhost:3000
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434
      - DEFAULT_MODELS=deepseek-r1:1.5b
    depends_on:
      - ollama
    networks:
      - ollama-network

networks:
  ollama-network:
    driver: bridge